### ISSUE TITLE
Error: Cannot convert value of type 'String' to expected argument type 'Event'

### ISSUE THREAD

**Issue by NishanthMurugan** [apptentive/apptentive-kit-ios#17]
As per given document in readme, we used

` Apptentive.shared.engage("purchase_complete", from: self) // where `self` is a UIViewController instance.
}`

But above statement prompting an error saying **Cannot convert value of type 'String' to expected argument type 'Event'**

![image](https://user-images.githubusercontent.com/30654850/172559212-b61e2dbc-c777-48a5-90e6-cde0b265fa77.png)

is it code issue or yet to publish the updated syntax under readme ?

**Comment by frankus** [comment]
The new `engage` method takes an `Event` object as an argument, but `Event` conforms to `ExpressibleByStringLiteral`, so passing a string literal should be working. 

If you are passing a variable of type `String`, see the note here: https://learn.apptentive.com/knowledge-base/apptentive-kit-ios-integration/#using-a-variable-as-the-event-name

**Comment by NishanthMurugan** [comment]
Perfect. Thanks for the document link.
