### ISSUE TITLE
Crash in MessageConfiguration post migration from v5.3.4 to v6.0.2

### ISSUE THREAD

**Issue by kaushikmurthy** [apptentive/apptentive-kit-ios#19]
Hello,

We have migrated to the latest Apptentive SDK from v5.3.4 to v6.0.2, and we faced an issue while showing the Message Center.

We are facing a NULL pointer crash in MessageCenterConfiguration class where the branding is not fetched as part of the MessageCenterConfiguration. With the latest SDK version v6.0.2, it expects the branding field, but we are getting it NULL and hence we are unable to show the MessageCenter.
The branding field in MessageCenterConfiguration class was not present in the old SDK and we see this is being added in the new SDK. 

We also noticed hideBranding field in the Configuration class is set to FALSE by default in the latest SDK but it is set to TRUE in the old SDK without any change in the portal. We are not sure if the crash is because of the field being set to FALSE.

Can you please help us know how to resolve this issue?
Also, let us know if you need any other information.

Thanks,
Kaushik

**Comment by frankus** [comment]
Thank you for the report. We are gearing up to release 6.0.3 and will include a fix for this issue. 

In the meantime, I've added a `fix-branding` branch that includes a fix for this. If it's not too much trouble, it would be great if you could test it out and confirm that it fixes the issue for your app.

**Comment by frankus** [comment]
This should be resolved in the v6.0.3 release that just went out.
