### ISSUE TITLE
Changes were made that break integrations without notification or documentation.

### ISSUE THREAD

**Issue by jgresham-incomm** [apptentive/apptentive-kit-ios#23]
It appears that several properties were renamed or removed from the `UIKit+Apptentive.swift` file without properly deprecating or documenting the property change.  [Integration documentation](https://learn.apptentive.com/knowledge-base/apptentive-kit-ios-customization/#uikit-extensions) still refers to properties that are no longer available.  Further more, this was done on a minor version change so unless someone has the dependency as locked to a specific version this will break everyones build as it is typically safe to allow dependancies to be constricted as "up to next minor version"

**Comment by frankus** [comment]
We've restored the renamed properties in v6.0.5. We're very sorry for the inconvenience.
