### ISSUE TITLE
Apptentive Message Center showing the Attachment to the end user

### ISSUE THREAD

**Issue by KSugunan** [apptentive/apptentive-kit-ios#35]
After we upgraded the Apptentive library to the latest version from version 5.x, when we launch the message centre , the attached file is displayed to the end user and this behaviour was not observed in the older version of Apptentive. 
Verified the integration document and its clearly mentioned that 'Attachment will not be visible for the customer in Message centre'. This behaviour is noticed in both Android and and iOS platform after library update. After upgrade we were not seeing this behaviour. Started showing all of a sudden. Please refer the below screenshot.
<img width="463" alt="f5019a58-fd81-4abe-9c6b-660bb7493fa0" src="https://user-images.githubusercontent.com/118808912/203284510-9c57c8b1-17d6-4e02-b37c-58dbf743ef88.png">

As we are collecting logs through apptentive, we can't disable this feature in message centre. Can you please look in to this and provide a fix at the earliest. Any help will be appreciated. Please let me know incase you need any more info for the quick resolution. Thanks.

**Comment by frankus** [comment]
You're absolutely right that the message should not be showing in the end-user UI. We will investigate this ASAP.

**Comment by KSugunan** [comment]
We are not seeing the issue happening in both the platforms now. Can you please tell me is there any fix done for the issue? If so, can you please elaborate. It'll be really helpful to understand the issue better. Thanks.

**Comment by CaseyApptentive** [comment]
Hi @KSugunan, my team pushed out a fix. Can you give it a try and let us know if you're still seeing issues? 

The problem was a server side change that we recently made, so no SDK update is required to see the fix.

**Comment by KSugunan** [comment]
Verified the fix. We are not seeing the issue in both the platform. Thanks for the quick turnaround.
